#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width           1
bspc config window_gap             0

bspc config split_ratio            0.50
bspc config borderless_monocle     true
bspc config gapless_monocle        true

feh --no-fehbg --bg-fill $HOME/wallpaper.png
$HOME/.config/polybar/launch.sh &
dunst &
flameshot &

bspc rule -a Alacritty:pulsemixer state=floating
