#!/bin/zsh

# +-------+
# | utils |
# +-------+

alias ls="ls --color=auto"
alias ll="ls -lahF"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -i"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# +-----+
# | X11 |
# +-----+

alias xpropc="xprop | grep WM_CLASS"

# +-----+
# | ZSH |
# +-----+

alias sh="zsh"

# +-----------+
# | REFLECTOR |
# +-----------+

alias mirrorsync="sudo reflector --latest 100 --sort rate --save /etc/pacman.d/mirrorlist"
